# Generated by Django 4.1.6 on 2023-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
