# Generated by Django 4.1.6 on 2023-02-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_score_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='number',
        ),
    ]
