# Generated by Django 4.1.6 on 2023-02-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_remove_score_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='score',
            table='score',
        ),
    ]
