# Generated by Django 4.1.6 on 2023-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_alter_score_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='score',
            name='input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
