# Generated by Django 4.1.6 on 2023-02-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_remove_score_user_score_input_score_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='timestamp',
            new_name='created_timestamp',
        ),
    ]
